name: UlitmateShop
version: 0.1
main: com.hotmail.ownedwtf.UltimateShop.UltimateShop
description: a bukkit plugin to manage donations and votes.

commands:
    ultimateshop:
       usage: </command> <args> [optional args]
       aliases: [us]
       description: UltimateShop Command
    test: